//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalHistory
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Doctor
    {
        public int DoctorId { get; set; }
        public string Name { get; set; }
        [StringLength(18, ErrorMessage = "Must be between 3 to 18 characters", MinimumLength = 3)]
        public string Password { get; set; }
        public string City { get; set; }
        [RegularExpression(@"^([6-9]\d{9})$", ErrorMessage = "Invalid Mobile Number")]
        [Required]
        public string ContactNo { get; set; }
    }
}
