//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalHistory
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Document
    {
        public int DocumentId { get; set; }
        public int PatientId { get; set; }
        public int HistoryId { get; set; }
        public string Path { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public virtual History History { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
