//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalHistory
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Documents = new HashSet<Document>();
            this.Histories = new HashSet<History>();
        }
    
        public int PatientId { get; set; }
        public string Name { get; set; }
        [StringLength(18,ErrorMessage="Must be between 3 to 18 characters",MinimumLength =3)]
        public string Password { get; set; }
        public int Age { get; set; }
        [Display(Name="Blood Group")]
        [Required]
        public string BloodGroup { get; set; }
        public string Allergy { get; set; }
        [RegularExpression(@"^([6-9]\d{9})$",ErrorMessage = "Invalid Mobile Number")]
        [Required]
        public string ContactNo { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        [RegularExpression(@"^([1-9][0-9]{5})$",ErrorMessage= " Pincode should be of 6 digits")]
        public int Pincode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
    }
}
